name: My First Action
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Greet the world
        run: echo "Hello, GitHub Actions is working!"
